name: shefu
description: Offline recipes manager
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.9.1+260

environment:
  sdk: ^3.10.8

dependencies:
  file_picker: ^10.3.8
  flag: ^7.0.2
  flutter:
    sdk: flutter
  command_it: ^9.5.0
  go_router: ^17.0.1
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  fraction: ^5.0.5
  image: ^4.5.4
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  riverpod: ^3.1.0
  pinch_zoom: ^2.0.1
  csv: ^6.0.0
  shared_preferences: ^2.5.4
  google_mlkit_text_recognition: ^0.15.0
  country_picker: ^2.0.27
  tutorial_coach_mark: ^1.3.3
  logger: ^2.6.2
  image_picker: ^1.2.1
  html: ^0.15.6
  http: ^1.6.0
  audioplayers: ^6.5.1
  objectbox: ^5.1.0
  objectbox_flutter_libs: ^5.1.0
  wakelock_plus: ^1.4.0
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  youtube_player_flutter: ^9.1.3
  pdf: ^3.11.3
  share_plus: ^12.0.1
  printing: ^5.14.2
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  objectbox_generator: ^5.1.0
  test: ^1.26.3
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/nutrients/
    - assets/nutrients_full.csv
    - assets/conversions_full.csv
    - assets/notification-ping-335500.mp3 # from https://pixabay.com/sound-effects/notification-ping-335500/
